rule("Generated by https://github.com/adapap/OWScript") { Event { Ongoing - Global; }}
rule("Setup Global") {
   Event {
      Ongoing - Global;
   }
   Actions {
      Set Global Variable At Index(A, 0, Vector(-4.5, 6, -79.25));
      Set Global Variable At Index(A, 1, Append To Array(Append To Array(Append To Array(Append To Array(Empty Array, Vector(-18, 5.85, -77.25)), Null), 100), Null));
      Set Global Variable At Index(A, 2, Append To Array(Empty Array, Value In Array(Global Variable(A), 1)));
   }
}
rule("Setup Store Locations") {
   Event {
      Ongoing - Global;
   }
   Actions {
      Create Effect(All Players(Team(All)), Ring, White, Vector(-18, 5.85, -77.25), 1.5, Visible To);
      Create In-World Text(All Players(Team(All)), String("{0}: {1}", String("{0} {1}", String("Upgrade", Null, Null, Null), String("{0} {1}", String("Money", Null, Null, Null), String("Time", Null, Null, Null), Null), Null), 100, Null), Add(Vector(-18, 5.85, -77.25), Up), 1.5, Clip Against Surfaces, Visible To And String);
   }
}
rule("Setup Player") {
   Event {
      Ongoing - Each Player;
      All;
      All;
   }
   Actions {
      Set Player Variable At Index(Event Player, A, 0, 0);
      Set Player Variable At Index(Event Player, A, 1, 5);
      Set Player Variable At Index(Event Player, A, 2, 15);
      Set Player Variable At Index(Event Player, A, 3, 0);
      Set Player Variable At Index(Event Player, A, 4, 0);
      Set Player Variable At Index(Event Player, A, 5, 0);
      Set Player Variable At Index(Event Player, A, 6, 0);
      Set Player Variable At Index(Event Player, A, 7, 0);
      Set Player Variable At Index(Event Player, A, 8, Append To Array(Append To Array(Append To Array(Append To Array(Append To Array(Empty Array, Null), Null), Null), Null), Null));
      Set Player Variable At Index(Event Player, A, 9, False);
      Set Player Variable At Index(Event Player, A, 10, 0);
      Set Player Variable At Index(Event Player, A, 11, 0);
      Set Player Variable At Index(Event Player, A, 12, False);
      Create Hud Text(Event Player, String("{0}: {1}", String("Money", Null, Null, Null), Value In Array(Player Variable(Event Player, A), 0), Null), Null, Null, Top, 0, White, White, White, Visible To And String);
   }
}
rule("Exit Shop") {
   Event {
      Ongoing - Each Player;
      All;
      All;
   }
   Conditions {
      Compare(Distance Between(Event Player, Value In Array(Global Variable(A), 0)), <=, 1.5) == True;
   }
   Actions {
      Respawn(Event Player);
      Set Player Variable At Index(Event Player, A, 9, True);
      Set Player Variable At Index(Event Player, A, 10, 15);
      Create Hud Text(Event Player, String("{0}: {1}", String("Cooldown", Null, Null, Null), Value In Array(Player Variable(Event Player, A), 10), Null), Null, Null, Left, 0, White, White, White, Visible To And String);
      Set Player Variable At Index(Event Player, A, 11, Last Text Id);
   }
}
rule("Loop - Money") {
   Event {
      Ongoing - Each Player;
      All;
      All;
   }
   Conditions {
      Compare(Value In Array(Player Variable(Event Player, A), 12), !=, True) == True;
   }
   Actions {
      Set Player Variable At Index(Event Player, A, 0, Add(Value In Array(Player Variable(Event Player, A), 0), Value In Array(Player Variable(Event Player, A), 1)));
      Wait(3, Ignore Condition);
      Loop;
   }
}
rule("Loop - On Player Kill") {
   Event {
      Player Earned Elimination;
      All;
      All;
   }
   Conditions {
      Compare(Attacker, !=, Victim) == True;
   }
   Actions {
      Set Player Variable At Index(Event Player, A, 0, Add(Value In Array(Player Variable(Event Player, A), 0), Value In Array(Player Variable(Event Player, A), 2)));
   }
}
rule("Buy Money / Time") {
   Event {
      Ongoing - Each Player;
      All;
      All;
   }

   Conditions {
      Is Button Held(Event Player, Interact) == True;
      Compare(Distance Between(Event Player, Vector(-18, 5.85, -77.25)), <=, 1.25) == True;
      Compare(Value In Array(Player Variable(Event Player, A), 0), >=, 100) == True;
      Compare(Value In Array(Player Variable(Event Player, A), 1), <, 2499) == True;
   }
   Actions {
      Set Player Variable At Index(Event Player, A, 0, Subtract(Value In Array(Player Variable(Event Player, A), 0), 100));
      Set Player Variable At Index(Event Player, A, 1, Add(Value In Array(Player Variable(Event Player, A), 1), 2));
      Small Message(Event Player, String("{0} {1}", String("Upgrade", Null, Null, Null), String("Bought", Null, Null, Null), Null));
      Play Effect(Event Player, Ring Explosion, White, Vector(-18, 5.85, -77.25), 3);
      Skip If(Compare(Is Button Held(Event Player, Crouch), !=, True), 2);
      Wait(0.016, Ignore Condition);
      Loop If Condition Is True;
   }
}