class Token:
    """Stores token information such as data and line number."""
    def __init__(self, type, value, line, column):
        self.type = type
        self.value = value
        self.line = line
        self.column = column

    def __repr__(self):
        return f'<{self.type}: {self.value} ({self.line}:{self.column})>'

ALIASES = {
    'CONST': {
        'CHATEAU GUILLARD': 'CHÂTEAU GUILLARD',
        'CUR ELEM': 'CURRENT ARRAY ELEMENT',
        'EVERYONE': 'ALL PLAYERS(TEAM(ALL))',
        'LUCIO': 'LÚCIO',
        'ON EACH PLAYER': 'ONGOING - EACH PLAYER',
        'ON GLOBAL': 'ONGOING - GLOBAL',
        'TORBJORN': 'TORBJÖRN',
        'VISIBLE TO POSITION AND RADIUS': 'VISIBLE TO, POSITION, AND RADIUS',
        'VISIBLE TO POSITION AND STRING': 'VISIBLE TO, POSITION, AND STRING'
    },
    'VALUE': {
        'ABS': 'ABSOLUTE VALUE',
        'ANY TRUE': 'IS TRUE FOR ANY',
        'ALL TRUE': 'IS TRUE FOR ALL',
        'ARRAY CONTAINS': 'ARRAY CONTAINS',
        'COS': 'COSINE FROM DEGREES',
        'COSR': 'COSINE FROM RADIANS',
        'FILTER': 'FILTERED ARRAY',
        'LOS': 'IS IN LINE OF SIGHT',
        'INDEX': 'INDEX OF ARRAY VALUE',
        'PLAYERS IN RADIUS': 'PLAYERS WITHIN RADIUS',
        'ROUND': 'ROUND TO INTEGER',
        'SIN': 'SINE FROM DEGREES',
        'SINR': 'SINE FROM RADIANS'
    },
    'ACTION': {
        'BIG MSG': 'BIG MESSAGE',
        'HUD': 'CREATE HUD TEXT',
        'MSG': 'SMALL MESSAGE',
        'SET HERO': 'START FORCING PLAYER TO BE HERO',
        'SMALL MSG': 'SMALL MESSAGE',
        'WORLD TEXT': 'CREATE IN-WORLD TEXT'
    }
}
MAPS = ["Black Forest", "Blizzard World", "Busan", "Castillo", "Château Guillard", "Dorado", "Ecopoint: Antarctica", "Eichenwalde", "Hanamura", "Havana", "Hollywood", "Horizon Lunar Colony", "Ilios", "Junkertown", "King\'s Row", "Lijiang Tower", "Necropolis", "Nepal", "Numbani", "Oasis", "Paris", "Petra", "Rialto", "Route 66", "Temple of Anubis", "Volskaya Industries", "Watchpoint: Gibraltar", "Ayutthaya", "Busan Downtown", "Busan Sanctuary", "Ilios Lighthouse", "Ilios Ruins", "Ilios Well", "Lijiang Control Center", "Lijiang Garden", "Lijiang Night Market", "Nepal Sanctum", "Nepal Shrine", "Nepal Village", "Oasis City Center", "Oasis Gardens", "Oasis University"]
CONST = ['ABILITY 1', 'ABILITY 2', 'ABORT WHEN FALSE', 'ABSOLUTE VALUE', 'ACKNOWLEDGE', 'ADD', 'ALL BARRIERS BLOCK LOS', 'ALL DEAD PLAYERS', 'ALL HEROES', 'ALL LIVING PLAYERS', 'ALL PLAYERS NOT ON OBJECTIVE', 'ALL PLAYERS ON OBJECTIVE', 'ALL PLAYERS', 'ALL TEAMS', 'ALL', 'ALLOWED HEROES', 'ALTITUDE OF', 'ANA', 'ANGLE DIFFERENCE', 'APPEND TO ARRAY', 'ARRAY CONTAINS', 'ARRAY SLICE', 'ARROW: DOWN', 'ARROW: LEFT', 'ARROW: RIGHT', 'ARROW: UP', 'ASHE', 'ASLEEP', 'ASTERISK', 'ATTACKER', 'BACKWARD', 'BAD AURA SOUND', 'BAD AURA', 'BAD EXPLOSION', 'BAD PICKUP EFFECT', 'BAPTISTE', 'BARRIERS DO NOT BLOCK LOS', 'BASTION', 'BEACON SOUND', 'BLUE', 'BOLT', 'BRIGITTE', 'BUFF EXPLOSION SOUND', 'BUFF IMPACT SOUND', 'BURNING', 'CANCEL CONTRARY MOTION', 'CHECKMARK', 'CIRCLE', 'CLIP AGAINST SURFACES', 'CLOSEST PLAYER TO', 'CLOUD', 'CLUB', 'COMPARE', 'CONTROL MODE SCORING PERCENTAGE', 'CONTROL MODE SCORING TEAM', 'COSINE FROM DEGREES', 'COSINE FROM RADIANS', 'COUNT OF', 'CROSS PRODUCT', 'CROUCH', 'CURRENT ARRAY ELEMENT', 'D.VA', 'DEBUFF IMPACT SOUND', 'DECAL SOUND', 'DESTINATION AND DURATION', 'DESTINATION AND RATE', 'DIAMOND', 'DIRECTION AND TURN RATE', 'DIRECTION FROM ANGLES', 'DIRECTION TOWARDS', 'DISTANCE BETWEEN', 'DIVIDE', 'DIZZY', 'DO NOT CLIP', 'DOOMFIST', 'DOT PRODUCT', 'DOWN', 'EMOTE DOWN', 'EMOTE LEFT', 'EMOTE RIGHT', 'EMOTE UP', 'EMPTY ARRAY', 'ENEMIES', 'ENEMY BARRIERS BLOCK LOS', 'ENERGY SOUND', 'ENTITY EXISTS', 'EVENT DAMAGE', 'EVENT PLAYER', 'EVENT WAS CRITICAL HIT', 'EXCLAMATION MARK', 'EXPLOSION SOUND', 'EYE POSITION', 'EYE', 'FACING DIRECTION OF', 'FALSE', 'FARTHEST PLAYER FROM', 'FILTERED ARRAY', 'FIRE', 'FIRST OF', 'FLAG POSITION', 'FLAG', 'FORWARD', 'FROZEN', 'GENJI', 'GLOBAL VARIABLE', 'GOOD AURA SOUND', 'GOOD AURA', 'GOOD EXPLOSION', 'GOOD PICKUP EFFECT', 'GREEN', 'GROUP UP', 'HACKED', 'HALO', 'HANZO', 'HAPPY', 'HAS SPAWNED', 'HAS STATUS', 'HEALTH PERCENT', 'HEALTH', 'HEART', 'HELLO', 'HERO ICON STRING', 'HERO OF', 'HERO', 'HORIZONTAL ANGLE FROM DIRECTION', 'HORIZONTAL ANGLE TOWARDS', 'HORIZONTAL FACING ANGLE OF', 'HORIZONTAL SPEED OF', 'IGNORE CONDITION', 'INCORPORATE CONTRARY MOTION', 'INDEX OF ARRAY VALUE', 'INTERACT', 'INVINCIBLE', 'IS ALIVE', 'IS ASSEMBLING HEROES', 'IS BETWEEN ROUNDS', 'IS BUTTON HELD', 'IS COMMUNICATING ANY EMOTE', 'IS COMMUNICATING ANY VOICE LINE', 'IS COMMUNICATING ANY', 'IS COMMUNICATING', 'IS CONTROL MODE POINT LOCKED', 'IS CROUCHING', 'IS CTF MODE IN SUDDEN DEATH', 'IS DEAD', 'IS FIRING PRIMARY', 'IS FIRING SECONDARY', 'IS FLAG AT BASE', 'IS FLAG BEING CARRIED', 'IS GAME IN PROGRESS', 'IS HERO BEING PLAYED', 'IS IN AIR', 'IS IN LINE OF SIGHT', 'IS IN SETUP', 'IS IN SPAWN ROOM', 'IS IN VIEW ANGLE', 'IS MATCH COMPLETE', 'IS MOVING', 'IS OBJECTIVE COMPLETE', 'IS ON GROUND', 'IS ON OBJECTIVE', 'IS ON WALL', 'IS PORTRAIT ON FIRE', 'IS STANDING', 'IS TEAM ON DEFENSE', 'IS TEAM ON OFFENSE', 'IS TRUE FOR ALL', 'IS TRUE FOR ANY', 'IS USING ABILITY 1', 'IS USING ABILITY 2', 'IS USING ULTIMATE', 'IS WAITING FOR PLAYERS', 'JUMP', 'JUNKRAT', 'KNOCKED DOWN', 'LAST CREATED ENTITY', 'LAST DAMAGE MODIFICATION ID', 'LAST DAMAGE OVER TIME ID', 'LAST HEAL OVER TIME ID', 'LAST OF', 'LAST TEXT ID', 'LEFT', 'LIGHT SHAFT', 'LOCAL VECTOR OF', 'LÚCIO', 'MATCH ROUND', 'MATCH TIME', 'MAX HEALTH', 'MAX', 'MCCREE', 'MEI', 'MERCY', 'MIN', 'MODULO', 'MOIRA', 'MOON', 'MULTIPLY', 'NEAREST WALKABLE POSITION', 'NEED HEALING', 'NO', 'NONE', 'NORMALIZE', 'NULL', 'NUMBER OF DEAD PLAYERS', 'NUMBER OF DEATHS', 'NUMBER OF ELIMINATIONS', 'NUMBER OF FINAL BLOWS', 'NUMBER OF HEROES', 'NUMBER OF LIVING PLAYERS', 'NUMBER OF PLAYERS ON OBJECTIVE', 'NUMBER OF PLAYERS', 'NUMBER', 'OBJECTIVE INDEX', 'OBJECTIVE POSITION', 'OFF', 'ONGOING - EACH PLAYER', 'ONGOING - GLOBAL', 'OPPOSITE TEAM OF', 'ORB', 'ORISA', 'PAYLOAD POSITION', 'PAYLOAD PROGRESS PERCENTAGE', 'PHARAH', 'PHASED OUT', 'PICK-UP SOUND', 'PLAYER CARRYING FLAG', 'PLAYER CLOSEST TO RETICLE', 'PLAYER DEALT DAMAGE', 'PLAYER DEALT FINAL BLOW', 'PLAYER DIED', 'PLAYER EARNED ELIMINATION', 'PLAYER TOOK DAMAGE', 'PLAYER VARIABLE', 'PLAYERS IN SLOT', 'PLAYERS IN VIEW ANGLE', 'PLAYERS ON HERO', 'PLAYERS WITHIN RADIUS', 'PLUS', 'POINT CAPTURE PERCENTAGE', 'POISON 2', 'POISON', 'POSITION AND RADIUS', 'POSITION OF', 'POSITION', 'PRIMARY FIRE', 'PURPLE', 'QUESTION MARK', 'RADIOACTIVE', 'RAISE TO POWER', 'RANDOM INTEGER', 'RANDOM REAL', 'RANDOM VALUE IN ARRAY', 'RANDOMIZED ARRAY', 'RAY CAST HIT NORMAL', 'RAY CAST HIT PLAYER', 'RAY CAST HIT POSITION', 'REAPER', 'RECEIVERS AND DAMAGERS', 'RECEIVERS DAMAGERS AND DAMAGE PERCENT', 'RECYCLE', 'RED', 'REINHARDT', 'REMOVE FROM ARRAY', 'RESTART WHEN TRUE', 'RIGHT', 'RING EXPLOSION SOUND', 'RING EXPLOSION', 'RING THICK', 'RING THIN', 'RING', 'ROADHOG', 'ROOTED', 'ROTATION AND TRANSLATION', 'ROTATION', 'ROUND TO INTEGER', 'SAD', 'SCORE OF', 'SECONDARY FIRE', 'SINE FROM DEGREES', 'SINE FROM RADIANS', 'SKULL', 'SLOT 0', 'SLOT 1', 'SLOT 10', 'SLOT 11', 'SLOT 2', 'SLOT 3', 'SLOT 4', 'SLOT 5', 'SLOT 6', 'SLOT 7', 'SLOT 8', 'SLOT 9', 'SLOT OF', 'SMOKE SOUND', 'SOLDIER: 76', 'SOMBRA', 'SORTED ARRAY', 'SPADE', 'SPARKLES SOUND', 'SPARKLES', 'SPEED OF IN DIRECTION', 'SPEED OF', 'SPHERE', 'SPIRAL', 'SQUARE ROOT', 'STOP', 'STRING', 'STUNNED', 'SUBTRACT', 'SURFACES AND ALL BARRIERS', 'SURFACES AND ENEMY BARRIERS', 'SURFACES', 'SYMMETRA', 'TEAM 1', 'TEAM 2', 'TEAM OF', 'TEAM SCORE', 'TEAM', 'THANKS', 'THROTTLE OF', 'TO NEAREST', 'TO PLAYER', 'TO WORLD', 'TOP', 'TORBJÖRN', 'TOTAL TIME ELAPSED', 'TRACER', 'TRASHCAN', 'TRUE', 'ULTIMATE CHARGE PERCENT', 'ULTIMATE STATUS', 'ULTIMATE', 'UNKILLABLE', 'UP', 'VALUE IN ARRAY', 'VECTOR TOWARDS', 'VECTOR', 'VELOCITY OF', 'VERTICAL ANGLE FROM DIRECTION', 'VERTICAL ANGLE TOWARDS', 'VERTICAL FACING ANGLE OF', 'VERTICAL SPEED OF', 'VICTIM', 'VISIBLE TO AND POSITION', 'VISIBLE TO AND STRING', 'VISIBLE TO, POSITION, AND RADIUS', 'VISIBLE TO, POSITION AND STRING', 'VISIBLE TO', 'VOICE LINE DOWN', 'VOICE LINE LEFT', 'VOICE LINE RIGHT', 'VOICE LINE UP', 'WARNING', 'WHITE', 'WIDOWMAKER', 'WINSTON', 'WORLD VECTOR OF', 'WRECKING BALL', 'X COMPONENT OF', 'X', 'Y COMPONENT OF', 'YELLOW', 'Z COMPONENT OF', 'ZARYA', 'ZENYATTA']
CONST.extend(ALIASES.get('CONST').keys())
CONST.extend(map(lambda x: x.replace('\'', '\'\'').upper(), MAPS))
VALUE = ['ABSOLUTE VALUE', 'ADD', 'ALL DEAD PLAYERS', 'ALL LIVING PLAYERS', 'ALL PLAYERS NOT ON OBJECTIVE', 'ALL PLAYERS ON OBJECTIVE', 'ALL PLAYERS', 'ALLOWED HEROES', 'ALTITUDE OF', 'ANGLE DIFFERENCE', 'APPEND TO ARRAY', 'ARRAY SLICE', 'CLOSEST PLAYER TO', 'COMPARE', 'CONTROL MODE SCORING PERCENTAGE', 'COSINE FROM DEGREES', 'COSINE FROM RADIANS', 'COUNT OF', 'CROSS PRODUCT', 'DIRECTION FROM ANGLES', 'DIRECTION TOWARDS', 'DISTANCE BETWEEN', 'DIVIDE', 'DOT PRODUCT', 'ENTITY EXISTS', 'EVENT DAMAGE', 'EYE POSITION', 'FACING DIRECTION OF', 'FARTHEST PLAYER FROM', 'FILTERED ARRAY', 'FIRST OF', 'FLAG POSITION', 'GLOBAL VARIABLE', 'HAS SPAWNED', 'HAS STATUS', 'HEALTH PERCENT', 'HEALTH', 'HERO ICON STRING', 'HERO OF', 'HERO', 'HORIZONTAL ANGLE FROM DIRECTION', 'HORIZONTAL ANGLE TOWARDS', 'HORIZONTAL FACING ANGLE OF', 'HORIZONTAL SPEED OF', 'INDEX OF ARRAY VALUE', 'IS ALIVE', 'IS BUTTON HELD', 'IS COMMUNICATING ANY EMOTE', 'IS COMMUNICATING ANY VOICE LINE', 'IS COMMUNICATING ANY', 'IS COMMUNICATING', 'IS CROUCHING', 'IS DEAD', 'IS FIRING PRIMARY', 'IS FIRING SECONDARY', 'IS FLAG AT BASE', 'IS FLAG BEING CARRIED', 'IS HERO BEING PLAYED', 'IS IN AIR', 'IS IN LINE OF SIGHT', 'IS IN SPAWN ROOM', 'IS IN VIEW ANGLE', 'IS MOVING', 'IS OBJECTIVE COMPLETE', 'IS ON GROUND', 'IS ON OBJECTIVE', 'IS ON WALL', 'IS PORTRAIT ON FIRE', 'IS STANDING', 'IS TEAM ON DEFENSE', 'IS TEAM ON OFFENSE', 'IS TRUE FOR ALL', 'IS TRUE FOR ANY', 'IS USING ABILITY 1', 'IS USING ABILITY 2', 'IS USING ULTIMATE', 'LAST DAMAGE MODIFICATION ID', 'LAST DAMAGE OVER TIME ID', 'LAST HEAL OVER TIME ID', 'LAST OF', 'LAST TEXT ID', 'LOCAL VECTOR OF', 'MATCH ROUND', 'MATCH TIME', 'MAX HEALTH', 'MAX', 'MIN', 'MODULO', 'MULTIPLY', 'NEAREST WALKABLE POSITION', 'NORMALIZE', 'NUMBER OF DEAD PLAYERS', 'NUMBER OF DEATHS', 'NUMBER OF ELIMINATIONS', 'NUMBER OF FINAL BLOWS', 'NUMBER OF HEROES', 'NUMBER OF LIVING PLAYERS', 'NUMBER OF PLAYERS ON OBJECTIVE', 'NUMBER OF PLAYERS', 'NUMBER', 'OBJECTIVE INDEX', 'OBJECTIVE POSITION', 'OPPOSITE TEAM OF', 'PAYLOAD PROGRESS PERCENTAGE', 'PLAYER CARRYING FLAG', 'PLAYER CLOSEST TO RETICLE', 'PLAYER VARIABLE', 'PLAYERS IN SLOT', 'PLAYERS IN VIEW ANGLE', 'PLAYERS ON HERO', 'PLAYERS WITHIN RADIUS', 'POINT CAPTURE PERCENTAGE', 'POSITION OF', 'RAISE TO POWER', 'RANDOM INTEGER', 'RANDOM REAL', 'RANDOM VALUE IN ARRAY', 'RANDOMIZED ARRAY', 'RAY CAST HIT NORMAL', 'RAY CAST HIT PLAYER', 'RAY CAST HIT POSITION', 'REMOVE FROM ARRAY', 'ROUND TO INTEGER', 'SCORE OF', 'SINE FROM DEGREES', 'SINE FROM RADIANS', 'SLOT OF', 'SORTED ARRAY', 'SPEED OF IN DIRECTION', 'SPEED OF', 'SQUARE ROOT', 'SUBTRACT', 'TEAM OF', 'TEAM SCORE', 'TEAM', 'THROTTLE OF', 'TOTAL TIME ELAPSED', 'ULTIMATE CHARGE PERCENT', 'VALUE IN ARRAY', 'VECTOR TOWARDS', 'VECTOR', 'VELOCITY OF', 'VERTICAL ANGLE FROM DIRECTION', 'VERTICAL ANGLE TOWARDS', 'VERTICAL FACING ANGLE OF', 'VERTICAL SPEED OF', 'WORLD VECTOR OF', 'X COMPONENT OF', 'Y COMPONENT OF', 'Z COMPONENT OF']
VALUE.extend(ALIASES.get('VALUE').keys())
ACTION = ['ABORT IF CONDITION IS FALSE', 'ABORT IF CONDITION IS TRUE', 'ABORT IF', 'ABORT', 'ALLOW BUTTON', 'APPLY IMPULSE', 'BIG MESSAGE', 'CHASE GLOBAL VARIABLE AT RATE', 'CHASE GLOBAL VARIABLE OVER TIME', 'CHASE PLAYER VARIABLE AT RATE', 'CHASE PLAYER VARIABLE OVER TIME', 'CLEAR STATUS', 'COMMUNICATE', 'CREATE EFFECT', 'CREATE HUD TEXT', 'CREATE ICON', 'CREATE IN-WORLD TEXT', 'DAMAGE', 'DECLARE MATCH DRAW', 'DECLARE PLAYER VICTORY', 'DECLARE ROUND VICTORY', 'DECLARE TEAM VICTORY', 'DESTROY ALL EFFECTS', 'DESTROY ALL HUD TEXT', 'DESTROY ALL ICONS', 'DESTROY ALL IN-WORLD TEXT', 'DESTROY EFFECT', 'DESTROY HUD TEXT', 'DESTROY ICON', 'DESTROY IN-WORLD TEXT', 'DISABLE BUILT-IN GAME MODE ANNOUNCER', 'DISABLE BUILT-IN GAME MODE COMPLETION', 'DISABLE BUILT-IN GAME MODE MUSIC', 'DISABLE BUILT-IN GAME MODE RESPAWNING', 'DISABLE BUILT-IN GAME MODE SCORING', 'DISABLE DEATH SPECTATE ALL PLAYERS', 'DISABLE DEATH SPECTATE TARGET HUD', 'DISALLOW BUTTON', 'ENABLE BUILT-IN GAME MODE ANNOUNCER', 'ENABLE BUILT-IN GAME MODE COMPLETION', 'ENABLE BUILT-IN GAME MODE MUSIC', 'ENABLE BUILT-IN GAME MODE RESPAWNING', 'ENABLE BUILT-IN GAME MODE SCORING', 'ENABLE DEATH SPECTATE ALL PLAYERS', 'ENABLE DEATH SPECTATE TARGET HUD', 'GO TO ASSEMBLE HEROES', 'HEAL', 'KILL', 'LOOP IF CONDITION IS FALSE', 'LOOP IF CONDITION IS TRUE', 'LOOP IF', 'LOOP', 'MODIFY GLOBAL VARIABLE', 'MODIFY PLAYER SCORE', 'MODIFY PLAYER VARIABLE', 'MODIFY TEAM SCORE', 'PAUSE MATCH TIME', 'PLAY EFFECT', 'PRELOAD HERO', 'PRESS BUTTON', 'RESET PLAYER HERO AVAILABILITY', 'RESPAWN', 'RESURRECT', 'SET ABILITY 1 ENABLED', 'SET ABILITY 2 ENABLED', 'SET AIM SPEED', 'SET DAMAGE DEALT', 'SET DAMAGE RECEIVED', 'SET FACING', 'SET GLOBAL VARIABLE AT INDEX', 'SET GLOBAL VARIABLE', 'SET GRAVITY', 'SET HEALING DEALT', 'SET HEALING RECEIVED', 'SET INVISIBLE', 'SET MATCH TIME', 'SET MAX HEALTH', 'SET MOVE SPEED', 'SET OBJECTIVE DESCRIPTION', 'SET PLAYER ALLOWED HEROES', 'SET PLAYER SCORE', 'SET PLAYER VARIABLE AT INDEX', 'SET PLAYER VARIABLE', 'SET PRIMARY FIRE ENABLED', 'SET PROJECTILE GRAVITY', 'SET PROJECTILE SPEED', 'SET RESPAWN MAX TIME', 'SET SECONDARY FIRE ENABLED', 'SET SLOW MOTION', 'SET STATUS', 'SET TEAM SCORE', 'SET ULTIMATE ABILITY ENABLED', 'SET ULTIMATE CHARGE', 'SKIP IF', 'SKIP', 'SMALL MESSAGE', 'START ACCELERATING', 'START CAMERA', 'START DAMAGE MODIFICATION', 'START DAMAGE OVER TIME', 'START FACING', 'START FORCING PLAYER TO BE HERO', 'START FORCING SPAWN ROOM', 'START FORCING THROTTLE', 'START HEAL OVER TIME', 'START HOLDING BUTTON', 'STOP ACCELERATING', 'STOP ALL DAMAGE MODIFICATIONS', 'STOP ALL DAMAGE OVER TIME', 'STOP ALL HEAL OVER TIME', 'STOP CAMERA', 'STOP CHASING GLOBAL VARIABLE', 'STOP CHASING PLAYER VARIABLE', 'STOP DAMAGE MODIFICATION', 'STOP DAMAGE OVER TIME', 'STOP FACING', 'STOP FORCING PLAYER TO BE HERO', 'STOP FORCING SPAWN ROOM', 'STOP FORCING THROTTLE', 'STOP HEAL OVER TIME', 'STOP HOLDING BUTTON', 'TELEPORT', 'UNPAUSE MATCH TIME', 'WAIT']
ACTION.extend(ALIASES.get('ACTION').keys())
OWID = CONST + VALUE + ACTION + MAPS
OWID.sort(key=len, reverse=True)

FUNCTIONS = VALUE + ACTION
FUNCTIONS.sort(key=len, reverse=True)
CONST.sort(key=len, reverse=True)
# print('|'.join(FUNCTIONS))
# print('|'.join(CONST))

class Tokens:
    """Mapping of token names to regular expressions."""
    COMMENT : r'(\/\*(.|[\n])*?\*\/\n*?|\/\/[^\n]*\n*?)'
    COMPARE : r'(>=|<=|==|!=|>|<)'
    ASSIGN : r'(=|\+=|-=|\*=|\/=|^=|%=)'
    TIME : r'([0-9]+(\.[0-9]+)?)(ms|s|min)'
    FLOAT : r'\-?[0-9]+\.[0-9]+'
    INTEGER : r'\-?[0-9]+'
    PLUS : r'\+'
    MINUS : r'\-'
    TIMES : r'\*'
    DIVIDE : r'\/'
    POW : r'\^'
    MOD : r'%'
    AT : r'@'
    COMMA : r','
    LPAREN : r'\('
    RPAREN : r'\)'
    LBRACK : r'\['
    RBRACK : r'\]'
    STRING : r'("[^\\\r\n\f]*?"|\'[^\\\r\n\f]*?\')'
    F_STRING : r'(`[^\\\r\n\f]*?`)'
    IMPORT : r'#IMPORT\b'
    IF : r'IF\b'
    ELIF : r'ELIF\b'
    ELSE : r'ELSE\b'
    WHILE : r'WHILE\b'
    FOR : r'FOR\b'
    NOT_IN : r'NOT IN\b'
    IN : r'IN\b'
    NOT : r'NOT\b'
    AND : r'AND\b'
    OR : r'OR\b'
    PVAR : r'PVAR\b'
    GVAR : r'GVAR\b'
    DISABLED : r'DISABLED\b'
    RETURN : r'RETURN\b'
    RULE : r'RULE\b'
    OWID : fr'(?<!\.)({"|".join(OWID)})(?=([\b\s\n\(\),\.\]]|:\n))'
    ANNOTATION : r'[_a-zA-Z0-9][_a-zA-Z0-9]*:(?!\n)'
    RULEBLOCK : r'(EVENT|CONDITIONS|ACTIONS)\b'
    NAME : r'[_a-zA-Z][_\-a-zA-Z0-9]*'
    WHITESPACE : r'[ \t]+'
    NEWLINE : r'[\r\n\f]+'
    SEMI : r';'
    COLON : r':'
    DOT : r'\.'