import re
class Token:
    """Stores token information such as data and line number."""
    def __init__(self, type, value, line, column):
        self.type = type
        self.value = value
        self.line = line
        self.column = column

    def __repr__(self):
        return f'<{self.type}: {self.value} ({self.line}:{self.column})'

ALIASES = [
    'ABS',
    'ANY TRUE',
    'ALL TRUE',
    'BIG MSG',
    'COS',
    'COSR',
    'CUR ELEM',
    'HUD',
    'INDEX',
    'LUCIO',
    'MSG',
    'ON GLOBAL',
    'ON EACH PLAYER',
    'PLAYERS IN RADIUS',
    'ROUND',
    'SIN',
    'SINR',
    'SMALL MSG',
    'TORBJORN'
]
ALIASES.sort(key=len, reverse=True)

class Tokens:
    """Mapping of token names to regular expressions."""
    ASSIGN : r'(=|\+=|-=|\*=|\/=|^=|%=)'
    STRING : r'"[^\\\r\n\f]*"'
    F_STRING : r'`[^\\\r\n\f]*"'
    FLOAT : r'[0-9]+\.[0-9]+'
    INTEGER : r'[0-9]+'
    ANNOTATION : r'[_a-zA-Z0-9][_a-zA-Z0-9]*:'
    CONST : r'(RECEIVERS, DAMAGERS, AND DAMAGE PERCENT|VISIBLE TO, POSITION, AND RADIUS|VISIBLE TO, POSITION, AND STRING|IS CONTROL MODE POINT LOCKED|IS CTF MODE IN SUDDEN DEATH|SURFACES AND ENEMY BARRIERS|CONTROL MODE SCORING TEAM|PLAYER EARNED ELIMINATION|SURFACES AND ALL BARRIERS|DESTINATION AND DURATION|PLAYER DEALT FINAL BLOW|EVENT WAS CRITICAL HIT|IS WAITING FOR PLAYERS|RECEIVERS AND DAMAGERS|CURRENT ARRAY ELEMENT|ONGOING - EACH PLAYER|VISIBLE TO AND STRING|DESTINATION AND RATE|IS ASSEMBLING HEROES|IS GAME IN PROGRESS|LAST CREATED ENTITY|PLAYER DEALT DAMAGE|POSITION AND RADIUS|PLAYER TOOK DAMAGE|IS BETWEEN ROUNDS|IS MATCH COMPLETE|RESTART WHEN TRUE|ABORT WHEN FALSE|IGNORE CONDITION|ONGOING - GLOBAL|PAYLOAD POSITION|GOOD AURA SOUND|BAD AURA SOUND|SPARKLES SOUND|PICK-UP SOUND|WRECKING BALL|BEACON SOUND|ENERGY SOUND|EVENT PLAYER|DECAL SOUND|EMPTY ARRAY|IS IN SETUP|LIGHT SHAFT|PLAYER DIED|SMOKE SOUND|SOLDIER: 76|ALL HEROES|VISIBLE TO|WIDOWMAKER|GOOD AURA|REINHARDT|ATTACKER|BACKWARD|BAD AURA|BAPTISTE|BRIGITTE|DOOMFIST|SPARKLES|SURFACES|SYMMETRA|TORBJÖRN|ZENYATTA|BASTION|FORWARD|JUNKRAT|ROADHOG|WINSTON|MCCREE|PHARAH|PURPLE|REAPER|SOMBRA|SPHERE|STRING|TEAM 1|TEAM 2|TRACER|VICTIM|YELLOW|CLOUD|FALSE|GENJI|GREEN|HANZO|LÚCIO|MERCY|MOIRA|ORISA|RIGHT|WHITE|ZARYA|ASHE|BLUE|D.VA|DOWN|LEFT|NONE|NULL|RING|TRUE|ALL|ANA|MEI|OFF|ORB|RED|UP)'
    ACTION : r'(DISABLE BUILT-IN GAME MODE COMPLETION|DISABLE BUILT-IN GAME MODE RESPAWNING|DISABLE BUILT-IN GAME MODE ANNOUNCER|ENABLE BUILT-IN GAME MODE COMPLETION|ENABLE BUILT-IN GAME MODE RESPAWNING|ENABLE BUILT-IN GAME MODE ANNOUNCER|DISABLE BUILT-IN GAME MODE SCORING|DISABLE DEATH SPECTATE ALL PLAYERS|DISABLE DEATH SPECTATE TARGET HUD|ENABLE BUILT-IN GAME MODE SCORING|ENABLE DEATH SPECTATE ALL PLAYERS|DISABLE BUILT-IN GAME MODE MUSIC|ENABLE DEATH SPECTATE TARGET HUD|CHASE GLOBAL VARIABLE OVER TIME|CHASE PLAYER VARIABLE OVER TIME|ENABLE BUILT-IN GAME MODE MUSIC|START FORCING PLAYER TO BE HERO|RESET PLAYER HERO AVAILABILITY|STOP FORCING PLAYER TO BE HERO|CHASE GLOBAL VARIABLE AT RATE|CHASE PLAYER VARIABLE AT RATE|STOP ALL DAMAGE MODIFICATIONS|SET GLOBAL VARIABLE AT INDEX|SET PLAYER VARIABLE AT INDEX|SET ULTIMATE ABILITY ENABLED|STOP CHASING GLOBAL VARIABLE|STOP CHASING PLAYER VARIABLE|ABORT IF CONDITION IS FALSE|ABORT IF CONDITION IS TRUE|LOOP IF CONDITION IS FALSE|SET SECONDARY FIRE ENABLED|DESTROY ALL IN-WORLD TEXT|LOOP IF CONDITION IS TRUE|SET OBJECTIVE DESCRIPTION|SET PLAYER ALLOWED HEROES|START DAMAGE MODIFICATION|STOP ALL DAMAGE OVER TIME|SET PRIMARY FIRE ENABLED|START FORCING SPAWN ROOM|STOP DAMAGE MODIFICATION|STOP ALL HEAL OVER TIME|STOP FORCING SPAWN ROOM|DECLARE PLAYER VICTORY|MODIFY GLOBAL VARIABLE|MODIFY PLAYER VARIABLE|SET PROJECTILE GRAVITY|START DAMAGE OVER TIME|START FORCING THROTTLE|DECLARE ROUND VICTORY|DESTROY IN-WORLD TEXT|GO TO ASSEMBLE HEROES|SET ABILITY 1 ENABLED|SET ABILITY 2 ENABLED|STOP DAMAGE OVER TIME|STOP FORCING THROTTLE|CREATE IN-WORLD TEXT|DECLARE TEAM VICTORY|DESTROY ALL HUD TEXT|SET HEALING RECEIVED|SET PROJECTILE SPEED|SET RESPAWN MAX TIME|START HEAL OVER TIME|START HOLDING BUTTON|DESTROY ALL EFFECTS|MODIFY PLAYER SCORE|SET DAMAGE RECEIVED|SET GLOBAL VARIABLE|SET PLAYER VARIABLE|SET ULTIMATE CHARGE|STOP HEAL OVER TIME|STOP HOLDING BUTTON|DECLARE MATCH DRAW|START ACCELERATING|UNPAUSE MATCH TIME|DESTROY ALL ICONS|MODIFY TEAM SCORE|SET HEALING DEALT|STOP ACCELERATING|DESTROY HUD TEXT|PAUSE MATCH TIME|SET DAMAGE DEALT|SET PLAYER SCORE|CREATE HUD TEXT|DISALLOW BUTTON|SET SLOW MOTION|DESTROY EFFECT|SET MATCH TIME|SET MAX HEALTH|SET MOVE SPEED|SET TEAM SCORE|APPLY IMPULSE|CREATE EFFECT|SET AIM SPEED|SET INVISIBLE|SMALL MESSAGE|ALLOW BUTTON|CLEAR STATUS|DESTROY ICON|PRELOAD HERO|PRESS BUTTON|START CAMERA|START FACING|BIG MESSAGE|COMMUNICATE|CREATE ICON|PLAY EFFECT|SET GRAVITY|STOP CAMERA|STOP FACING|SET FACING|SET STATUS|RESURRECT|ABORT IF|TELEPORT|LOOP IF|RESPAWN|SKIP IF|DAMAGE|ABORT|HEAL|KILL|LOOP|SKIP|WAIT)'
    VALUE : r'(CONTROL MODE SCORING PERCENTAGE|HORIZONTAL ANGLE FROM DIRECTION|IS COMMUNICATING ANY VOICE LINE|NUMBER OF PLAYERS ON OBJECTIVE|VERTICAL ANGLE FROM DIRECTION|ALL PLAYERS NOT ON OBJECTIVE|LAST DAMAGE MODIFICATION ID|PAYLOAD PROGRESS PERCENTAGE|HORIZONTAL FACING ANGLE OF|IS COMMUNICATING ANY EMOTE|NEAREST WALKABLE POSITION|PLAYER CLOSEST TO RETICLE|ALL PLAYERS ON OBJECTIVE|HORIZONTAL ANGLE TOWARDS|LAST DAMAGE OVER TIME ID|NUMBER OF LIVING PLAYERS|POINT CAPTURE PERCENTAGE|VERTICAL FACING ANGLE OF|ULTIMATE CHARGE PERCENT|LAST HEAL OVER TIME ID|NUMBER OF DEAD PLAYERS|NUMBER OF ELIMINATIONS|VERTICAL ANGLE TOWARDS|DIRECTION FROM ANGLES|IS FLAG BEING CARRIED|IS OBJECTIVE COMPLETE|NUMBER OF FINAL BLOWS|PLAYERS IN VIEW ANGLE|PLAYERS WITHIN RADIUS|RANDOM VALUE IN ARRAY|RAY CAST HIT POSITION|SPEED OF IN DIRECTION|FARTHEST PLAYER FROM|INDEX OF ARRAY VALUE|IS COMMUNICATING ANY|IS HERO BEING PLAYED|PLAYER CARRYING FLAG|COSINE FROM DEGREES|COSINE FROM RADIANS|FACING DIRECTION OF|HORIZONTAL SPEED OF|IS FIRING SECONDARY|IS IN LINE OF SIGHT|IS PORTRAIT ON FIRE|RAY CAST HIT NORMAL|RAY CAST HIT PLAYER|ALL LIVING PLAYERS|IS TEAM ON DEFENSE|IS TEAM ON OFFENSE|IS USING ABILITY 1|IS USING ABILITY 2|OBJECTIVE POSITION|TOTAL TIME ELAPSED|CLOSEST PLAYER TO|DIRECTION TOWARDS|IS FIRING PRIMARY|IS USING ULTIMATE|NUMBER OF PLAYERS|REMOVE FROM ARRAY|SINE FROM DEGREES|SINE FROM RADIANS|VERTICAL SPEED OF|ALL DEAD PLAYERS|ANGLE DIFFERENCE|DISTANCE BETWEEN|HERO ICON STRING|IS COMMUNICATING|IS IN SPAWN ROOM|IS IN VIEW ANGLE|NUMBER OF DEATHS|NUMBER OF HEROES|OPPOSITE TEAM OF|RANDOMIZED ARRAY|ROUND TO INTEGER|APPEND TO ARRAY|GLOBAL VARIABLE|IS FLAG AT BASE|IS ON OBJECTIVE|IS TRUE FOR ALL|IS TRUE FOR ANY|LOCAL VECTOR OF|OBJECTIVE INDEX|PLAYER VARIABLE|PLAYERS IN SLOT|PLAYERS ON HERO|WORLD VECTOR OF|ABSOLUTE VALUE|ALLOWED HEROES|FILTERED ARRAY|HEALTH PERCENT|IS BUTTON HELD|RAISE TO POWER|RANDOM INTEGER|VALUE IN ARRAY|VECTOR TOWARDS|X COMPONENT OF|Y COMPONENT OF|Z COMPONENT OF|CROSS PRODUCT|ENTITY EXISTS|FLAG POSITION|EVENT DAMAGE|EYE POSITION|IS CROUCHING|IS ON GROUND|LAST TEXT ID|SORTED ARRAY|ALL PLAYERS|ALTITUDE OF|ARRAY SLICE|DOT PRODUCT|HAS SPAWNED|IS STANDING|MATCH ROUND|POSITION OF|RANDOM REAL|SQUARE ROOT|THROTTLE OF|VELOCITY OF|HAS STATUS|IS ON WALL|MATCH TIME|MAX HEALTH|TEAM SCORE|IS IN AIR|IS MOVING|NORMALIZE|COUNT OF|FIRST OF|IS ALIVE|MULTIPLY|SCORE OF|SPEED OF|SUBTRACT|COMPARE|HERO OF|IS DEAD|LAST OF|SLOT OF|TEAM OF|DIVIDE|HEALTH|MODULO|NUMBER|VECTOR|HERO|TEAM|ADD|MAX|MIN)'
    RULEBLOCK : r'(EVENT|CONDITIONS|ACTIONS)'
    ALIAS : f'({"|".join(ALIASES)})'
    RULE : 'RULE'
    IF : 'IF'
    ELIF : 'ELIF'
    ELSE : 'ELSE'
    WHILE : 'WHILE'
    FOR : 'FOR'
    IN : 'IN'
    NOT : 'NOT'
    AND : 'AND'
    OR : 'OR'
    PVAR : 'PVAR'
    GVAR : 'GVAR'
    NAME : r'[_a-zA-Z][_\-a-zA-Z0-9]*'
    WHITESPACE : r'[ \t]+'
    NEWLINE : r'[\r\n\f]+'
    COMMENT : r'(/\*(.|[\n])*?\*/|\/\/[^\n]*)'